# Generated by Django 2.2.1 on 2019-06-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_management', '0003_auto_20190610_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillgroup',
            name='skill_group_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
