# Generated by Django 2.2.1 on 2019-06-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_management', '0004_skillgroup_skill_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_department',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
