# Generated by Django 2.2.1 on 2019-06-10 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill_management', '0005_employee_employee_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_no', models.IntegerField(default=0)),
                ('department_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill_management.Department'),
        ),
    ]
