# Generated by Django 2.2.1 on 2019-06-26 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill_management', '0006_auto_20190610_1442'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeeskilllist',
            unique_together={('employee', 'skill')},
        ),
    ]
